// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoodHabits.Database.Migrations
{
    [DbContext(typeof(GoodHabitsDbContext))]
    [Migration("20241228205211_accPartnetIdNull")]
    partial class accPartnetIdNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountabilityPartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountabilityPartnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Do some exercise",
                            IsCompleted = false,
                            Name = "Exercise"
                        },
                        new
                        {
                            Id = 2,
                            AccountabilityPartnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Read a book",
                            IsCompleted = false,
                            Name = "Read"
                        },
                        new
                        {
                            Id = 3,
                            AccountabilityPartnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Meditate for 10 minutes",
                            IsCompleted = false,
                            Name = "Meditate"
                        },
                        new
                        {
                            Id = 4,
                            AccountabilityPartnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Write a blog post",
                            IsCompleted = false,
                            Name = "Write"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
