services:
  dev-env:
    container_name: dev-env
    build:
      context: ./dev-env
    volumes:
      - "..:/workspace"
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    stdin_open: true # docker run -i
    tty: true # docker run -t
  db:
    container_name: postgresDB
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - habit-db-volume:/var/lib/postgresql/data/
    env_file:
      - postgresql/postgresql.env
volumes:
  habit-db-volume: null